server:
  port: 8082
spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: xxxxxxxxxxxxxxxxxxx
    username: zhangkehui11@qq.com
    port: 25

#rabbitmq配置
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.64.101
    port: 5672
    listener:
      simple:
        #手动确认
        acknowledge-mode: manual


redis:
  timeout: 10000ms        #连接超时时间
  host: 127.0.0.1         #redis服务器地址
  port: 6379              #redis服务器端口
  database: 0             #redis数据库 默认选0号数据库
  lettuce:
    pool:
      max-active: 1024            #最大连接数
      max-wait: 10000ms           #最大连接阻塞等待时间，单位毫秒，默认-1
      max-idle: 200               #最大空闲连接 默认8
      min-idle: 5                 #最小空闲连接 默认0
